### PR TITLE
Bug Fix - Filter component element

### PR DESCRIPTION
**Pull request by Aaronfischer**
#### What does this pull request do?
Fixes visual/layout bug related to the filter components all stacking within the first table heading.

#### What are the relevant issues?
#46 

#### Any background context you want to provide?
Should be merged before any outstanding PR.

#### Definition of Done:
*Each should be selected to indicate consideration for applicability and/or completion.*

- [x] Does this PR fully satisfy the scope as outlined in the referenced issue(s)?
- [x] Is there appropriate test coverage?
- [x] Is static analysis resulting in a satisfactory score?
- [x] If adding new dependencies, does pip requirements need to be updated?
- [x] Has the change log been updated?

### CODE REVIEW

**Comment by morgan** [comment]
@Aaronfischer Let's get this current.

**Comment by morgan** [comment]
@Aaronfischer Haha, more conflicts. :)

**Comment by morgan** [comment]
@Aaronfischer Looks like we have some tests failing.

**Comment by Aaronfischer** [comment]
@morgan Alright, got it. 😁

**Pull request merged**
