### PR TITLE
Upgrade to ember 2.10

### PR DESCRIPTION
**Pull request by Aaronfischer**
#### What does this pull request do?
Upgrades to ember 2.10.

#### What are the relevant issues?
#73 

#### Any background context you want to provide?
Also upgrade ember-cli-mirage to 0.2.4
NOTE: We need to drop support for anything under ember 2.8 on this specific version.
(There are some inconsistencies/incompatibilities that ember made in regards to the component lifecycle)

#### Definition of Done:
*Each should be selected to indicate consideration for applicability and/or completion.*

- [x] Does this PR fully satisfy the scope as outlined in the referenced issue(s)?
- [x] Is there appropriate test coverage?
- [x] Is static analysis resulting in a satisfactory score?
- [x] If adding new dependencies, does pip requirements need to be updated?
- [x] Has the change log been updated?

### CODE REVIEW

**Comment by Aaronfischer** [comment]
@morgan This upgrades to ember-cli 2.10.0 and also resolves our outstanding multi-request bug.

(Looks like some changes were made between an older ember version and a new one in how the observers are fired when the component is destroyed/rebuilt.)

**Comment by Aaronfischer** [comment]
@morgan I'd love to get this rolled in, as I noted in the background above, is it possible to setup a separate version(tag?), a lot has happened between what we originally built tabular in (like 1.13) and 2.10.

**Comment by Aaronfischer** [comment]
@morgan If your in a "peer review" mood, do you think you could take a look at this PR and https://github.com/caxiam/ember-tabular/pull/77 I'd like to cut 2 releases, a "pre" (current `master`) and a "post" which would be this PR and #77.

**Comment by morgan** [comment]
@Aaronfischer Easy breezy

**Pull request merged**
