### PR TITLE
Styling - Add wrapper classes

### PR DESCRIPTION
**Pull request by Aaronfischer**
#### What does this pull request do?
Add additional wrapper classes for styling purposes.

#### What are the relevant issues?
N/A

#### Any background context you want to provide?
N/A

#### Definition of Done:
*Each should be selected to indicate consideration for applicability and/or completion.*

- [x] Does this PR fully satisfy the scope as outlined in the referenced issue(s)?
- [x] Is there appropriate test coverage?
- [x] Is static analysis resulting in a satisfactory score?
- [x] If adding new dependencies, does pip requirements need to be updated?
- [x] Has the change log been updated?

### CODE REVIEW

**Comment by Aaronfischer** [comment]
@morgan If/when you get a chance I'd like to get this integrated, some other work relying on this integration to visually show properly.
(looks like the failed test is due to phantomJS bitbucket repo error.)

**Comment by Aaronfischer** [comment]
@morgan This has been updated and removed ember-canary from the testing.

**Comment by Aaronfischer** [comment]
@morgan 👀

**Comment by morgan** [comment]
@Aaronfischer 👍

**Pull request merged**
